[Variables]
bgH=120
dotY=23
highlightColor=254,210,70,230

[Title]
Meter=String
MeterStyle=allText
FontSize=18
FontColor=#highlightColor#
Text=Crypto-Widget
X=83
Y=10

[Version]
Meter=String
MeterStyle=allText
FontColor=#textMainColor#
FontSize=11
Text=RVN#Version#
X=-2R
Y=1r

[Author]
Meter=String
MeterStyle=allText
FontColor=#textMainColor#
FontSize=10
Text="RVN Mining Pool Monitor"
X=85
Y=37

[LicenseHeader]
Meter=String
MeterStyle=headerText
Text=License
X=85
Y=27R

[LicenseText]
Meter=String
MeterStyle=subText
FontSize=10
Text="Free, but donations welcome :)#CRLF#@RichyP85 on"
X=r
Y=-2r

[Twitter]
Meter=Image
ImageName=#@#Images\Twitter.png
PreserveAspectRatio=1
X=180
Y=60
W=80
H=80
SolidColor=47,47,47,1
AntiAlias=1
LeftMouseDownAction=https://twitter.com/RichyP85

